apiVersion: batch/v1
kind: Job
metadata:
  name: command-args-only-args
spec:
  template:
    metadata:
      name: command-args-only-args
    spec:
      restartPolicy: Never
      containers:
      - image: ibotty/kube-command-args-test:latest
        name: kube-command-args-test
        args:
        - one
        - two
        imagePullPolicy: Always
